version: 2.1

# Require cypress
orbs:
  cypress: cypress-io/cypress@1

executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"

# Define the jobs we want to run for this project
jobs:
  pull-and-build-main:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./redxamapp/scripts/backendDeploy.sh production"
  pull-and-build-staging:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP_STAGING "./redxamapp/scripts/backendDeploy.sh staging"
  pull-and-build-develop:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP_DEVELOP "./redxamapp/scripts/backendDeploy.sh development"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build-main:
          filters:
            branches:
              only:
                - main
      - pull-and-build-staging:
          filters:
            branches:
              only:
                - staging
      - pull-and-build-develop:
          filters:
            branches:
              only:
                - develop
  test-frontend:
    jobs:
      - cypress/run:
          yarn: true
          store_artifacts: true
          working_directory: "packages/frontend"
          executor: with-chrome
          browser: chrome
          build: NEXT_PUBLIC_PROD_BASE_URL=https://api.redxam.com NEXT_PUBLIC_DEV_BASE_URL=http://localhost:5005 SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          record: true
